"use client";
import { useAppDispatch, useAppSelector } from "@/store";
import { addOne, substractOne, initCounterState } from "@/store/counter/counterSlice";
import { useEffect, useState } from "react";

interface Props {
    value: number
}

export interface CounterResponse {
  count: number;
}

const getApiCounter = async ():Promise<CounterResponse> => {
  const data = await fetch('/api/counter')
  .then((response ) => response.json())

  return data 
}// Generated by https://quicktype.io

export const CartCounter = ({value} : Props) => {
  // const [counter, setCounter] = useState(value);
  const count = useAppSelector( state => state.counter.count)
  const dispatch = useAppDispatch()

  useEffect(() => {
    getApiCounter()
    .then(({count}) => dispatch(initCounterState(count)) )
 
  }, [dispatch])
  
  // useEffect(() => {
  //     dispatch(initCounterState(value))
  // }, [dispatch, value])
  return (
    <>
      <span className="text-9xl"> {count} </span>
      <div className="flex gap-2">
        <button
          onClick={() => dispatch( substractOne())}
          className="flex items-center justify-center rounded-xl bg-gray-900 text-white hover:bg-gray-600 transition-all w-[100px] mr-2"
        >
          -1
        </button>
        <button
          onClick={() => dispatch( addOne())}
          className="flex items-center justify-center rounded-xl bg-gray-900 text-white hover:bg-gray-600 transition-all w-[100px] mr-2"
        >
          +1
        </button>
      </div>
    </>
  );
};
